### ISSUE TITLE
Needs better handling of local vs server login

### ISSUE THREAD

**Issue by maksimlikharev** [apim-haufe-io/wicked.portal-auth#1]
Bumped into following situation, mistakenly entered username/password into local login screen, got error, realized that I'm in a wrong screen, went to oauth2 login, authorized and got 409 error that user already exists.

```
2018-10-05 22:17:16.978 +00:00:       'duplicate key value violates unique constraint "users_email_idx"' } }
2018-10-05 22:17:17.025 +00:00: { Error: A user with the email address "api.admin@xxxx.com" already exists in the system. Please log in using the existing user's identity.

```

This is somehow related to migrated user accounts, I cannot reproduce that on fresh user.
In the same time when I go directly to oauth2 after the migration, all is fine.

**Comment by maksimlikharev** [comment]
problem is, this user was never local, it was never created, but was migrated.

This is how I reproduced that, we have `api.admin@xxx.com` in dynamic dir.

1. migrate data
 1a. I can see that user in wicked.users;
2. login with local, using this user name and password, no success
3. login with federated login, error 409

I can send you actual data, if needed

**Comment by maksimlikharev** [comment]
Let me clarify that,

it is not in initialUsers in globals.json

this user is Oauth2 user, it is present in: `users\2aaf8b8c472d70abad220f5ae3320b59608c8798.json`

```

{
  "id": "2aaf8b8c472d70abad220f5ae3320b59608c8798",
  "customId": "0d9eab60-ad2f-11e7-9850-25acadd08df9",
  "firstName": "API Portal",
  "lastName": "Admin",
  "validated": true,
  "email": "api.admin@xxx.com",
  "password": null,

```


after migration I see that user in wicked.users table.

I think as far as migration, it's correct, what is not correct, when I use local login with `api.admin@xxx.com` Wicked marks that as a local user, prohibiting further Oauth2 login with that id.

**Comment by DonMartin76** [comment]
Are you using a `defaultPrefix` in the `customIdMappings` section? And if so, does it match the auth method ID you have specified for your OAuth2 IdP?

This use case is what the `defaultPrefix` is meant for. Can you check that please?

**Comment by maksimlikharev** [comment]
I use whatever default:

```
"customIdMappings": {
    "defaultPrefix": null,
    "prefixes": {
      "Google": "google",
      "Github": "github"
    }
  }
```

are you saying `defaultPrefix` should be our IDP name and all users will be migrated as oauth2?

**Comment by DonMartin76** [comment]
Correct. So, if your auth method ID is `oauth2` (or `clarivate`), the `defaultPrefix` must also be `oauth2` (or `clarivate`, accordingly). Or whatever auth method corresponds to the default OAuth2 IdP you had before.

**Comment by maksimlikharev** [comment]
yes, that helped, this is no longer highjacks network logins

I'm closing this issue
